services:
  clickhouse:
    image: clickhouse/clickhouse-server:latest
    ports:
      - "8123:8123"
      - "9000:9000"
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 1G
    ulimits:
      nofile:
        soft: 262144
        hard: 262144
